### ISSUE TITLE
What is the meaning of heartbeat icon in the upper right of the display?

### ISSUE THREAD

**Issue by wsanders** [mongonta0716/stackchan-bluetooth-simple#2]
Fun project!

I have installed the precompiled binary from the M5Stack Core2 loader and it works fine. I have no servos or microSD card attached to the Core2. When I start the program, before it is placed in Bluetooth mode, there is an animated heartbeat in the upper right of the display. I can't find where in the code this is setup. What does this heartbeat signify?

**Comment by mongonta0716** [comment]
The heart is an effect, to represent Expresstion::happy, with different facial expressions to represent the Bluetooth connection status and the happy singing.
The display is done with the M5Stack-Avatar library.

https://github.com/mongonta0716/stackchan-bluetooth-simple/blob/main/src/BluetoothA2DPSink_M5Speaker.hpp#L67-L132
